# Generated by Django 3.0.6 on 2020-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=32)),
                ('time', models.DateTimeField(verbose_name='received at time')),
                ('data', models.CharField(blank=True, max_length=5120)),
            ],
        ),
    ]
